### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gatarelib** [MarcioQuimbundo/uber_clone#2] opened 2019-04-26 14:38 UTC
Would be nice if you had good documentation

**Comment by MarcioQuimbundo** [comment] 2019-05-13 12:28
comming soon

**Comment by Hawaiideveloper** [comment] 2019-10-22 15:57
duplicate

**Comment by Hawaiideveloper** [comment] 2019-10-22 16:02
This issue resembles this one


https://github.com/MarcioQuimbundo/uber_clone/issues/4

**Comment by Hawaiideveloper** [comment] 2019-10-22 16:03
Issue is duplicate of this one:
https://github.com/MarcioQuimbundo/uber_clone/issues/1

**Closed as completed** 2020-06-30 10:17 UTC
